# Generated by Django 5.0.4 on 2024-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
