# Generated by Django 5.0.4 on 2024-06-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_news_category'),
        ('sponsor', '0003_favoritestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritestudent',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='favoritestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='backend.student'),
        ),
    ]
