# Generated by Django 5.0.4 on 2024-06-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_remove_favoritestudent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='slug',
        ),
    ]
