# Generated by Django 5.0.4 on 2024-05-18 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='donation',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='paidBy',
            new_name='donatedby',
        ),
        migrations.AddField(
            model_name='donate',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.CreateModel(
            name='DonateToStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationTitle', models.CharField(max_length=255)),
                ('donationId', models.TextField(max_length=255)),
                ('productId', models.TextField(max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paymentMode', models.TextField(max_length=255)),
                ('donatedBy', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
    ]
