# Generated by Django 5.0.4 on 2024-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='students/')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('spo_cover', models.CharField(choices=[('School Fees', 'School Fees'), ('Clothes', 'Clothes'), ('Medicines', 'Medicines'), ('Food', 'Food')], max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
