# Generated by Django 5.0.4 on 2024-05-15 17:05

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
