# Generated by Django 5.0.4 on 2024-06-12 17:20

import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='projects/')),
                ('target', models.CharField(default='Project', max_length=255)),
                ('category', models.CharField(choices=[('Special Projects', 'Special Projects'), ('Regular Projects', 'Regular Projects'), ('Normal Projects', 'Normal Projects')], default='Regular Projects', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
