# Generated by Django 5.0.4 on 2024-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unactive', 'Unactive')], max_length=255),
        ),
    ]
