# Generated by Django 5.0.4 on 2024-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subTitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
