# Generated by Django 5.0.4 on 2024-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_projectdetails'),
        ('home', '0004_monthlyprayer_alter_donation_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
