# Generated by Django 5.0.4 on 2024-05-15 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_student_image_remove_student_spo_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='spo_cover',
        ),
        migrations.AddField(
            model_name='student',
            name='spo_cover',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
