# Generated by Django 5.0.4 on 2024-06-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Vocational Training', 'Vocational Training'), ('Education', 'Education'), ('Tunga Women Initiative', 'Tunga Women Initiative'), ('Community Empowerment', 'Community Empowerment'), ('Medical Care', 'Medical Care')], max_length=255),
        ),
    ]
