# Generated by Django 5.0.4 on 2024-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_alter_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
