# Generated by Django 5.0.4 on 2024-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_student_spo_cover_student_spo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='spo_cover',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30),
        ),
    ]
