# Generated by Django 5.0.4 on 2024-06-15 17:45

import backend.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.student_image_path),
        ),
    ]
