# Generated by Django 5.0.4 on 2024-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_student_gender_alter_student_spo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spo_cover',
            field=models.CharField(choices=[('School Fees', 'School Fees'), ('Clothes', 'Clothes'), ('Medicines', 'Medicines'), ('Food', 'Food')], max_length=30),
        ),
    ]
