# Generated by Django 5.0.4 on 2024-06-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_category_project_categorys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categorys',
        ),
        migrations.RemoveField(
            model_name='project',
            name='targets',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Special Projects', 'Special Projects'), ('Regular Projects', 'Regular Projects'), ('Normal Projects', 'Normal Projects')], default='Regular Projects', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.CharField(default='Project', max_length=255),
        ),
    ]
