# Generated by Django 5.0.4 on 2024-06-15 18:11

import backend.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.blog_image_path),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.campaign_image_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.story_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='category',
            field=models.CharField(blank=True, choices=[('Special Projects', 'Special Projects'), ('Regular Projects', 'Regular Projects'), ('Normal Projects', 'Normal Projects')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.project_image_path),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.resource_image_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.resource_image_path),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.slide_image_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.team_image_path),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=backend.models.testimony_image_path),
        ),
    ]
