# Generated by Django 5.0.4 on 2024-06-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_project_categorys_remove_project_targets_and_more'),
    ]

    operations = [
    ]
