# Generated by Django 5.0.4 on 2024-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
