# Generated by Django 5.0.4 on 2024-06-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20240612_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='target',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='type',
        ),
    ]
