# Generated by Django 5.0.4 on 2024-05-18 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
