# Generated by Django 5.0.4 on 2024-05-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
    ]
