# Generated by Django 5.0.4 on 2024-05-18 12:53

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
