# Generated by Django 5.0.4 on 2024-05-18 14:43

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
