# Generated by Django 5.0.4 on 2024-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subTitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
