# Generated by Django 5.0.4 on 2024-05-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_blog_created_at_blog_is_published_blog_published_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
