# Generated by Django 5.0.4 on 2024-05-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_whatwedo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatWeDo',
        ),
    ]
