# Generated by Django 5.0.4 on 2024-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_news_slug_news_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('colored_logo', 'Colored Logo'), ('black_logo', 'Black Logo'), ('white_logo', 'White Logo'), ('favicon', 'Favicon')], default='favicon', max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
