# Generated by Django 5.0.4 on 2024-06-02 09:11

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_news_slug_news_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='logos/favicon/')),
                ('black_logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='logos/black/')),
                ('white_logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='logos/white/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
