# Generated by Django 5.0.4 on 2024-06-02 09:39

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={},
        ),
        migrations.RemoveField(
            model_name='logo',
            name='black_logo',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='white_logo',
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='logo',
            name='section',
            field=models.CharField(choices=[('favicon', 'Favicon'), ('black_logo', 'Black Logo'), ('white_logo', 'White Logo')], default='favicon', max_length=20, unique=True),
        ),
    ]
