# Generated by Django 5.0.4 on 2024-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='spo_cover',
        ),
        migrations.AlterField(
            model_name='logo',
            name='section',
            field=models.CharField(choices=[('color_logo', 'Colored Logo'), ('black_logo', 'Black Logo'), ('white_logo', 'White Logo'), ('favicon', 'Favicon')], default='favicon', max_length=20, unique=True),
        ),
    ]
