# Generated by Django 5.0.4 on 2024-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_logo_options_remove_logo_black_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
