# Generated by Django 5.0.4 on 2024-06-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_student_spo_cover_alter_logo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spo_cover',
            field=models.CharField(blank=True, choices=[('School Fees', 'School Fees'), ('Clothes', 'Clothes'), ('Medicines', 'Medicines'), ('Food', 'Food')], max_length=30, null=True),
        ),
    ]
