# Generated by Django 5.0.4 on 2024-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='section',
            field=models.CharField(choices=[('favicon', 'Favicon'), ('black_logo', 'Black Logo'), ('white_logo', 'White Logo'), ('color_logo', 'Color Logo')], default='favicon', max_length=20, unique=True),
        ),
    ]
