# Generated by Django 5.0.4 on 2024-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_student_spo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spo_cover',
            field=models.CharField(blank=True, choices=[('School Fees', 'School Fees'), ('Clothes', 'Clothes'), ('Medicines', 'Medicines'), ('Food', 'Food')], default='Food', max_length=30, null=True),
        ),
    ]
