# Generated by Django 5.0.4 on 2024-06-05 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_student_spo_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('org_name', models.CharField(max_length=255)),
                ('n_visitors', models.PositiveIntegerField()),
                ('req_visit', models.DateField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
