# Generated by Django 5.0.4 on 2024-06-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_visitingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitingrequest',
            old_name='approved',
            new_name='status',
        ),
    ]
