# Generated by Django 5.0.4 on 2024-06-06 12:42

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='campaigns/'),
        ),
    ]
