# Generated by Django 5.0.4 on 2024-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='title',
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('Privacy Policy', 'Privacy Policy'), ('Child Protection Policy', 'Child Protection Policy'), ('Terms & Conditions', 'Terms & Conditions')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
