# Generated by Django 5.0.4 on 2024-06-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_policy_title_policy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('privacy-policy', 'Privacy Policy'), ('child-protection-policy', 'Child Protection Policy'), ('terms-conditions', 'Terms & Conditions')], max_length=50),
        ),
    ]
