# Generated by Django 5.0.4 on 2024-06-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_policy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('Privacy Policy', 'Privacy Policy'), ('Child Protection Policy', 'Child Protection Policy'), ('Terms & Conditions', 'Terms & Conditions')], max_length=50),
        ),
    ]
