# Generated by Django 5.0.4 on 2024-06-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_policy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Local', 'Local'), ('Stateside', 'Stateside')], default='Local', max_length=20),
        ),
    ]
