# Generated by Django 5.0.4 on 2024-06-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Local', 'Local'), ('Stateside', 'Stateside')], max_length=20),
        ),
    ]
