# Generated by Django 5.0.4 on 2024-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Rwanda Staff', 'Rwanda Staff'), ('Stateside Staff', 'Stateside Staff')], max_length=20),
        ),
    ]
