# Generated by Django 5.0.4 on 2024-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaryName', models.CharField(max_length=255)),
                ('beneficiaryId', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donatedBy', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('paymentMode', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('beneficiaryAge', models.CharField(default='1', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDonationRecord',
        ),
    ]
