# Generated by Django 5.0.4 on 2024-06-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentsgifts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDonations',
        ),
    ]
