# Generated by Django 5.0.4 on 2024-06-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sendprayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPrayer',
        ),
    ]
