# Generated by Django 5.0.4 on 2024-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatetostudents',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donatetostudents',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
