# Generated by Django 5.0.4 on 2024-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_donategifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatetostudents',
            name='paymentMode',
            field=models.CharField(choices=[('School Fees', 'School Fees'), ('Clothes', 'Clothes'), ('Medicines', 'Medicines'), ('Food', 'Food')], max_length=40),
        ),
        migrations.AlterField(
            model_name='donatetostudents',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Successful', 'Successful')], default='Pending', max_length=40),
        ),
    ]
