# Generated by Django 5.0.4 on 2024-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_donatetostudents_paymentmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatetostudents',
            name='paymentMode',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=40),
        ),
        migrations.AlterField(
            model_name='donatetostudents',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Successful', 'Successful')], default='Pending', max_length=40),
        ),
    ]
