# Generated by Django 5.0.4 on 2024-06-10 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_donatetostudent_delete_donatetostudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatetostudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
