# Generated by Django 5.0.4 on 2024-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_donatetobeneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatetostudent',
            name='beneficiary',
            field=models.TextField(max_length=255),
        ),
    ]
