# Generated by Django 5.0.4 on 2024-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_donatetostudent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatetostudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
