# Generated by Django 5.0.4 on 2024-06-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_donatetostudent_beneficiary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonateToStudent',
            new_name='StudentDonation',
        ),
    ]
