# Generated by Django 5.0.4 on 2024-06-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_donatetostudent_studentdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatetobeneficiary',
            name='beneficiary',
        ),
        migrations.DeleteModel(
            name='StudentDonation',
        ),
        migrations.DeleteModel(
            name='DonateToBeneficiary',
        ),
    ]
