# Generated by Django 5.0.4 on 2024-06-10 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_donatetostudent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatetostudent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
