# Generated by Django 5.0.4 on 2024-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_donatetobeneficiary_beneficiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaryName', models.CharField(max_length=255)),
                ('beneficiaryId', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donatedBy', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('paymentMode', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=100)),
            ],
        ),
    ]
