# Generated by Django 5.0.4 on 2024-06-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_donatetostudent_created_at'),
    ]

    operations = [
    ]
