# Generated by Django 5.0.4 on 2024-05-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
