# Generated by Django 5.0.4 on 2024-05-26 14:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='testimonies/'),
        ),
    ]
