# Generated by Django 5.0.4 on 2024-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_testimony_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=100)),
                ('values', models.CharField(max_length=100)),
            ],
        ),
    ]
