# Generated by Django 5.0.4 on 2024-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_mvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvv',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mvv',
            name='values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mvv',
            name='vision',
            field=models.TextField(),
        ),
    ]
