# Generated by Django 5.0.4 on 2024-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_mvv_mission_alter_mvv_values_alter_mvv_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVisionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision'), ('values', 'Values')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='MVV',
        ),
    ]
