# Generated by Django 5.0.4 on 2024-05-29 15:05

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_missionvisionvalues_delete_mvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='whatwedo/icons/')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='whatwedo/images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
