# Generated by Django 5.0.4 on 2024-05-30 20:57

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='news/'),
        ),
    ]
