# Generated by Django 5.0.4 on 2024-06-03 08:51

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='message',
        ),
        migrations.AddField(
            model_name='testimony',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='logo',
            name='section',
            field=models.CharField(choices=[('color_logo', 'Colored Logo'), ('black_logo', 'Black Logo'), ('white_logo', 'White Logo'), ('favicon', 'Favicon')], default='favicon', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='missionvisionvalues',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
